import {useState,useEffect,useRef} from 'react';
import type {ReviewEntry,IdaStatus,LeftPaneState,RightPaneState} from './data/reviewData';
import TopBar from './components/rb/TopBar';
import FunctionList from './components/rb/FunctionList';
import CodePane from './components/rb/CodePane';
import BottomBar from './components/rb/BottomBar';
type Instance={instance:string;idb:string;input:string};
type State={entries:ReviewEntry[];active:string;loaded:boolean;scanning:boolean;scanMessage:string;idaStatus:IdaStatus;idaDb:string;instances:Instance[];settings:{reviewFile?:string;sourceRoot?:string;targetModule?:string};canUndo:boolean;demo:boolean};
type Inspection={entry:ReviewEntry;leftState:LeftPaneState;rightState:RightPaneState;error?:string};
const empty:State={entries:[],active:'',loaded:false,scanning:false,scanMessage:'',idaStatus:'disconnected',idaDb:'',instances:[],settings:{},canUndo:false,demo:false};
const token=location.hash.slice(1);
async function api<T>(action:string,body:object={}):Promise<T>{const response=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':token},body:JSON.stringify(body)});const result=await response.json();if(!result.ok)throw Error(result.error||'Request failed');return result.data;}
const btn='px-3 py-1.5 rounded border border-tn-border text-xs text-tn-text hover:bg-tn-surface disabled:opacity-40';
const field='w-full bg-tn-bg2 border border-tn-border rounded px-3 py-2 text-xs text-tn-text outline-none focus:border-tn-blue';

function Project({state,close,save,rescan}:{state:State;close:()=>void;save:(body:object)=>Promise<void>;rescan:()=>Promise<void>}){
 const[file,setFile]=useState(state.settings.reviewFile||''),[root,setRoot]=useState(state.settings.sourceRoot||''),[module,setModule]=useState(state.settings.targetModule||''),[instance,setInstance]=useState(state.instances.find(i=>i.idb===state.idaDb)?.instance||''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function browse(kind:string,set:(value:string)=>void){try{const r=await api<{path:string}>('browse',{kind});if(r.path)set(r.path);}catch(e){setError(String(e));}}
 async function submit(){setBusy(true);try{await save({reviewFile:file,sourceRoot:root,targetModule:module,instance});}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center"><div className="w-[580px] max-w-[95vw] rounded-lg border border-tn-border bg-tn-surface shadow-2xl overflow-hidden"><div className="px-6 py-4 bg-tn-bg2 border-b border-tn-border"><div className="text-tn-blue text-xs uppercase tracking-widest">C++ Review Workbench</div><h2 className="text-base mt-1">Project settings</h2></div><div className="p-6 space-y-4">
 <div><label className="text-xs text-tn-dim">Review list file</label><div className="flex gap-2 mt-1"><input aria-label="Review list file" className={field} value={file} onChange={e=>setFile(e.target.value)} placeholder="/projects/review_list"/><button className={btn} onClick={()=>browse('file',setFile)}>Browse</button></div></div>
 <div><label className="text-xs text-tn-dim">C++ source root</label><div className="flex gap-2 mt-1"><input aria-label="C++ source root" className={field} value={root} onChange={e=>setRoot(e.target.value)} placeholder="/projects/galaxcore"/><button className={btn} onClick={()=>browse('directory',setRoot)}>Browse</button></div></div>
 <div><label className="text-xs text-tn-dim">IDA instance</label><div className="flex gap-2 mt-1"><select aria-label="IDA instance" className={field} value={instance} onChange={e=>setInstance(e.target.value)}><option value="">Choose an IDA database (or read source offline)</option>{state.instances.map(i=><option key={i.instance} value={i.instance}>{i.idb}</option>)}</select><button className={btn} onClick={()=>rescan().catch(e=>setError(String(e)))}>Rescan</button></div></div>
 <div><label className="text-xs text-tn-dim">Module represented by this IDB</label><input aria-label="Target module" className={field+' mt-1'} value={module} onChange={e=>setModule(e.target.value)} placeholder="power2"/><p className="text-xs text-tn-dim mt-2">Load bridge.py in IDA first. Every function uses its own annotation mapping, not a fixed offset.</p></div>{error&&<p role="alert" className="text-xs text-tn-red">{error}</p>}
 </div><div className="flex justify-end gap-2 px-6 py-4 border-t border-tn-border"><button className={btn} disabled={busy} onClick={close}>Cancel</button><button className={btn+' bg-tn-blue !text-tn-bg font-semibold'} disabled={busy} onClick={submit}>{busy?'Opening...':'Open project'}</button></div></div></div>;
}

export default function App(){
 const[state,setState]=useState(empty),[ready,setReady]=useState(false),[settings,setSettings]=useState(false),[closing,setClosing]=useState(false);
 const[version,setVersion]=useState('All'),[author,setAuthor]=useState('All'),[module,setModule]=useState('All'),[status,setStatus]=useState('All'),[search,setSearch]=useState('');
 const[active,setActive]=useState(''),[entry,setEntry]=useState<ReviewEntry|null>(null),[left,setLeft]=useState<LeftPaneState>('failed'),[right,setRight]=useState<RightPaneState>('loading');
 const[error,setError]=useState(''),[busy,setBusy]=useState(false),[updated,setUpdated]=useState(''),[collapsed,setCollapsed]=useState(false),[split,setSplit]=useState(50),[sync,setSync]=useState(false);
 const[leftScroll,setLeftScroll]=useState(0),[rightScroll,setRightScroll]=useState(0);
 const seq=useRef(0),latest=useRef<ReviewEntry|null>(null),container=useRef<HTMLDivElement>(null),dragging=useRef(false),leftRef=useRef<HTMLDivElement|null>(null),rightRef=useRef<HTMLDivElement|null>(null),stateRef=useRef(state);stateRef.current=state;
 useEffect(()=>{let live=true;api<State>('state').then(s=>{if(live){setState(s);setReady(true);}}).catch(e=>{setError(String(e));setReady(true);});return()=>{live=false;};},[]);
 useEffect(()=>{let live=true;let timer:ReturnType<typeof setTimeout>;async function poll(){if(!settings&&!busy&&!document.hidden){const revision=seq.current;try{const s=await api<State>('state');if(live&&revision===seq.current)setState(old=>JSON.stringify(old)===JSON.stringify(s)?old:s);}catch(e){if(live)setError(String(e));}}if(live)timer=setTimeout(poll,state.scanning?1500:10000);}timer=setTimeout(poll,state.scanning?1500:10000);return()=>{live=false;clearTimeout(timer);};},[settings,busy,state.scanning]);
 useEffect(()=>{function move(e:MouseEvent){if(dragging.current&&container.current){const r=container.current.getBoundingClientRect();setSplit(Math.max(25,Math.min(75,(e.clientX-r.left)/r.width*100)));}}function up(){dragging.current=false;document.body.style.cursor='';}document.addEventListener('mousemove',move);document.addEventListener('mouseup',up);return()=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up);};},[]);
 async function inspect(id:string,candidate?:number){const request=++seq.current;setActive(id);setBusy(true);setError('');setLeft('loading');setRight('loading');if(latest.current?.id!==id){latest.current=null;setEntry(stateRef.current.entries.find(e=>e.id===id)||null);}try{const result=await api<Inspection>('inspect',{id,...(candidate===undefined?{}:{candidate})});if(request!==seq.current)return;if(result.leftState==='failed'&&latest.current?.id===id&&latest.current.pseudocode){result.entry.pseudocode=latest.current.pseudocode;setLeft('stale');}else setLeft(result.leftState);setRight(result.rightState);setEntry(result.entry);latest.current=result.entry;if(result.error)setError(result.error);if(result.leftState==='ok')setUpdated(new Date().toLocaleTimeString());}catch(e){if(request===seq.current){setError(String(e));setLeft(latest.current?.id===id?'stale':'failed');setRight('not-found');}}finally{if(request===seq.current)setBusy(false);}}
 useEffect(()=>{function refresh(){if(active&&!busy&&!settings)void inspect(active);}window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh);},[active,busy,settings]);
 const wasScanning=useRef(false);useEffect(()=>{if(wasScanning.current&&!state.scanning&&active)void inspect(active);wasScanning.current=state.scanning;},[state.scanning]);
 function filtered(rows:ReviewEntry[]){const q=search.trim().toLowerCase();return rows.filter(e=>(version==='All'||e.version===version)&&(author==='All'||e.author===author)&&(module==='All'||e.module===module)&&(status==='All'||e.status===status.toLowerCase())&&(!q||e.funcName.toLowerCase().includes(q)||e.address.toLowerCase().includes(q)));}
 const rows=filtered(state.entries),pinned=state.entries.find(e=>e.id===active)||null;
 function filter(set:(v:string)=>void,v:string){if(busy)return;seq.current++;set(v);setActive('');setEntry(null);latest.current=null;setLeft('failed');setError('');}
 async function mutate(action:string){if(busy)return;setBusy(true);setError('');const id=active;try{const s=await api<State>(action,{id});setState(s);stateRef.current=s;const options=filtered(s.entries),index=options.findIndex(e=>e.id===id),next=action==='undo'?s.entries.find(e=>e.id===s.active):options.slice(index+1).find(e=>e.status==='pending')||options.find(e=>e.status==='pending');if(next)await inspect(next.id);else{setActive('');setEntry(null);latest.current=null;}}catch(e){setError(String(e));setLeft('stale');}finally{setBusy(false);}}
 async function reconnect(){setState(s=>({...s,idaStatus:'connecting'}));setState(await api<State>('connect'));}
 async function project(body:object){seq.current++;const s=await api<State>('setup',body);setState(s);setSettings(false);setActive('');setEntry(null);latest.current=null;setVersion('All');setAuthor('All');setModule('All');setStatus('All');setError('');}
 async function reindex(){setBusy(true);setError('');try{setState(await api<State>('reindex'));setRight('indexing');setLeft('stale');}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function openTool(action:string){try{await api(action,{id:active});setLeft('stale');}catch(e){setError(String(e));}}
 const unique=(key:'version'|'author'|'module',data=state.entries)=>Array.from(new Set(data.map(e=>e[key]))).sort();
 return <div className="flex flex-col h-full bg-tn-bg">
 <div className="flex items-center justify-between px-3 h-8 bg-tn-bg2 border-b border-tn-border flex-shrink-0 select-none"><div className="text-[12px] font-bold tracking-widest text-tn-blue uppercase">C++ Review Workbench <span className="ml-2 font-normal text-tn-dim">LOCAL DESKTOP</span></div><div className="flex items-center gap-2"><span className="text-[12px] text-tn-dim">{updated&&`Updated ${updated}`}</span><button className={btn+' !py-0.5'} onClick={()=>setSync(!sync)}>{sync?'Sync on':'Sync scroll'}</button><button className={btn+' !py-0.5'} onClick={()=>setClosing(true)}>×</button></div></div>
 {state.demo&&<div className="bg-tn-yellow/10 text-tn-yellow text-xs px-4 py-1 border-b border-tn-yellow/30">DEMO — disposable example files and simulated IDA. No production files are used.</div>}
 <TopBar versions={unique('version')} authors={unique('author',state.entries.filter(e=>version==='All'||e.version===version))} modules={unique('module',state.entries.filter(e=>(version==='All'||e.version===version)&&(author==='All'||e.author===author)))} version={version} author={author} module={module} statusFilter={status} searchQuery={search} idaStatus={state.idaStatus} idaDb={state.idaDb.split(/[\\/]/).pop()||''} onVersion={v=>{filter(setVersion,v);setAuthor('All');setModule('All');}} onAuthor={v=>{filter(setAuthor,v);setModule('All');}} onModule={v=>filter(setModule,v)} onStatusFilter={v=>filter(setStatus,v)} onSearch={v=>filter(setSearch,v)} onReconnect={()=>reconnect().catch(e=>setError(String(e)))} onOpenSettings={()=>setSettings(true)}/>
 {(error||state.idaStatus==='disconnected')&&<div role="alert" className="px-4 py-2 bg-tn-yellow/10 text-tn-yellow border-b border-tn-yellow/30 text-xs">{error||'IDA is not connected. Load bridge.py in IDA, then choose its database and target module in Settings.'}</div>}
 {state.scanning&&<div className="px-4 py-1 text-xs text-tn-blue animate-pulse">Indexing source annotations…</div>}
 <div className="flex flex-1 min-h-0"><FunctionList entries={rows} currentId={active} pinnedId={active} collapsed={collapsed} onSelect={id=>{if(!busy)void inspect(id);}} onToggleCollapse={()=>setCollapsed(!collapsed)}/>
 {entry?<div ref={container} className="flex flex-1 min-w-0 min-h-0 overflow-hidden"><div className="flex flex-col min-w-0" style={{width:`${split}%`}}><CodePane side="ida" entry={entry} leftState={left} rightState={right} onOpenInIda={()=>openTool('jump')} onRefreshIda={()=>inspect(active)} onOpenInVsCode={()=>{}} onReload={()=>{}} onSelectCandidate={()=>{}} scrollRef={leftRef} syncScroll={sync} onScroll={sync?setLeftScroll:undefined} externalScrollTop={sync?rightScroll:undefined}/></div><div className="w-1 flex-shrink-0 bg-tn-border hover:bg-tn-blue/50 cursor-col-resize" onMouseDown={()=>{dragging.current=true;document.body.style.cursor='col-resize';}}/><div className="flex flex-col min-w-0" style={{width:`${100-split}%`}}><CodePane side="cpp" entry={entry} leftState={left} rightState={right} onOpenInIda={()=>{}} onRefreshIda={()=>{}} onOpenInVsCode={()=>openTool('editor')} onReload={reindex} onSelectCandidate={path=>inspect(active,entry.srcCandidates?.indexOf(path))} scrollRef={rightRef} syncScroll={sync} onScroll={sync?setRightScroll:undefined} externalScrollTop={sync?leftScroll:undefined}/></div></div>:<div className="flex-1 flex flex-col justify-center items-center gap-4 text-center px-6"><div className="text-tn-blue uppercase text-xs tracking-[0.25em]">C++ Review</div><h1 className="text-xl text-tn-text">{!ready?'Connecting to local service…':!state.loaded?'Open your review project':rows.length===0?'No functions in this selection':'Choose a function to review'}</h1><p className="text-tn-dim text-sm">{state.loaded?`${rows.filter(e=>e.status==='done').length} completed · ${rows.filter(e=>e.status==='pending').length} pending · ${rows.filter(e=>e.status==='skipped').length} skipped`:'Select a review list, C++ source root and your local IDA database.'}</p><div className="flex gap-2"><button className={btn} onClick={()=>setSettings(true)}>Project settings</button>{rows.some(e=>e.status==='pending')&&<button className={btn+' bg-tn-blue !text-tn-bg'} disabled={state.scanning} onClick={()=>inspect(rows.find(e=>e.status==='pending')!.id)}>Open next pending</button>}{state.loaded&&<button className={btn} onClick={()=>mutate('reset-skips')}>Reset skipped</button>}</div>{state.scanMessage&&<p className="text-xs text-tn-dim">{state.scanMessage}</p>}</div>}
 </div>
 <BottomBar pinnedEntry={pinned} viewEntry={entry} isViewingPinned={!entry||entry.id===active} saveError={error||null} canUndo={state.canUndo} canComplete={!!pinned&&pinned.status==='pending'&&left==='ok'&&right==='ok'&&state.idaStatus==='connected'} busy={busy||state.scanning} onPrev={()=>{const i=rows.findIndex(e=>e.id===active);if(i>0)void inspect(rows[i-1].id);}} onSkip={()=>mutate('skip')} onComplete={()=>mutate('complete')} onUndo={()=>mutate('undo')} onReturnToPinned={()=>inspect(active)}/>
 {settings&&<Project state={state} close={()=>setSettings(false)} save={project} rescan={reconnect}/>}
 {closing&&<div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center"><div className="rounded-lg bg-tn-surface border border-tn-border p-6"><h2 className="text-sm">Close this window?</h2><p className="text-xs text-tn-dim mt-2">Completed reviews are saved in your review list.</p><div className="flex justify-end gap-2 mt-5"><button autoFocus className={btn+' bg-tn-blue !text-tn-bg'} onClick={()=>setClosing(false)}>No</button><button className={btn} onClick={()=>api('close').catch(e=>setError(String(e)))}>Yes, close</button></div></div></div>}
 </div>;
}
