#!/bin/bash
KW_FATAL_ERROR='^ERROR:|fatal|segmentation fault'
KW_RUNTIME='Runtime:'
KW_WRITE_BIT_FINISH='write_bitstream finish'
KW_BGN_FINISH='translate bgn finish'
KW_DCP_PASS='DCP Compare PASS'
KW_DCP_FAIL='DCP Compare FAIL'
KW_CHECKSUM_FINISH='checksum_cmp finish!'